image: chaplean/php:7.1-no-xdebug

cache:
    paths:
        - vendor/

before_script:
    - composer install --prefer-dist --no-interaction

test:
    stage: test
    script:
        - phpdbg -qrr ./phpunit --configuration phpunit.xml.dist --colors=never --coverage-html coverage/ --coverage-text
    artifacts:
        paths:
            - coverage/
        expire_in: 1 day
